package com.vogella.tycho.reactor;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

public class ModuleListWriterTest {

	@Rule
	public TemporaryFolder folder = new TemporaryFolder();

	private final ModuleListWriter writer = new ModuleListWriter();

	@Test
	public void writesPathsRelativeToTheAggregator() throws Exception {
		Path root = folder.getRoot().toPath();

		Path file = writer.write(root, "build", List.of("bundle", "bundles/core"));

		assertEquals(root.resolve("build/pom.tycho"), file);
		assertEquals(List.of("../bundle", "../bundles/core"), modules(file));
	}

	@Test
	public void writesPathsAsTheyAreNextToTheRootPom() throws Exception {
		Path root = folder.getRoot().toPath();

		Path file = writer.write(root, ".", List.of("bundle"));

		assertEquals(root.resolve("pom.tycho"), file);
		assertEquals(List.of("bundle"), modules(file));
	}

	@Test
	public void keepsTheFileUntouchedWhenNothingChanged() throws Exception {
		Path root = folder.getRoot().toPath();
		Path file = writer.write(root, "build", List.of("bundle"));
		Files.setLastModifiedTime(file, java.nio.file.attribute.FileTime.fromMillis(0));

		writer.write(root, "build", List.of("bundle"));

		assertEquals(0, Files.getLastModifiedTime(file).toMillis());
	}

	@Test
	public void isNotMistakenForATychoGeneratedFile() throws Exception {
		Path file = writer.write(folder.getRoot().toPath(), "build", List.of("bundle"));

		// Tycho ignores its own generated lists, the marker must stay different
		assertTrue(Files.readString(file).startsWith("# Generated by tycho-build-project-reactor"));
	}

	private static List<String> modules(Path file) throws Exception {
		return Files.readAllLines(file).stream().filter(line -> !line.startsWith("#") && !line.isBlank()).toList();
	}
}
