/*******************************************************************************
 * Copyright (c) 2026 vogella GmbH and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package com.vogella.tycho.reactor;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import javax.inject.Named;
import javax.inject.Singleton;

/**
 * Writes the discovered modules as a {@code pom.tycho} file that tycho-build turns into an
 * aggregator.
 */
@Named
@Singleton
public class ModuleListWriter {

	/** Name of the aggregator folder below the reactor root, "." for the root itself. */
	public static final String AGGREGATOR_PROPERTY = "tycho.reactor.aggregator";

	public static final String DEFAULT_AGGREGATOR = "build";

	public static final String MODULE_LIST = "pom.tycho";

	private static final String HEADER = "# Generated by tycho-build-project-reactor, do not edit.";

	private static final String HEADER_HINT = "# The list is rebuilt from the folder structure on every Maven build.";

	/**
	 * Writes the module list of the given aggregator folder, creating the folder if needed, and
	 * returns the file. Nothing is written when the content is already up to date.
	 *
	 * @param modules module paths relative to the reactor root
	 */
	public Path write(Path root, String aggregator, List<String> modules) throws IOException {
		Path directory = ".".equals(aggregator) ? root : root.resolve(aggregator);
		String prefix = directory.equals(root) ? "" : relativePrefix(root, directory);
		List<String> lines = new ArrayList<>(List.of(HEADER, HEADER_HINT, ""));
		modules.stream().map(module -> prefix + module).forEach(lines::add);
		Path file = directory.resolve(MODULE_LIST);
		String content = String.join(System.lineSeparator(), lines) + System.lineSeparator();
		if (Files.isRegularFile(file) && content.equals(Files.readString(file, StandardCharsets.UTF_8))) {
			return file;
		}
		Files.createDirectories(directory);
		Files.writeString(file, content, StandardCharsets.UTF_8);
		return file;
	}

	/**
	 * Returns the {@code ../} prefix that leads from the aggregator folder back to the root.
	 */
	private static String relativePrefix(Path root, Path directory) {
		return "../".repeat(root.relativize(directory).getNameCount());
	}
}
